# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.2
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: dragojlovic.tadej@gmail.com
author_name: TadejDragojlovic
contract_name: coinflip
deployment_language: python
preset_name: starter
project_name: coinflip-game

